import type { LetterEntry } from "./types";

export const letterData: Record<string, LetterEntry> = {
  A: {
    word: "Apple",
    phoneme: "ahh",
    emoji: "🍎",
    color: "bg-coral-400",
    filterTheme: {
      shape: "apple",
      primaryColor: "#E63946",
      accentColor: "#2D6A4F",
      eyeColor: "#1D3557",
    },
  },
  B: {
    word: "Balloon",
    phoneme: "buh",
    emoji: "🎈",
    color: "bg-sky-400",
    filterTheme: {
      shape: "balloon",
      primaryColor: "#29B6F6",
      accentColor: "#FF6B63",
      eyeColor: "#01579B",
    },
  },
  C: {
    word: "Cat",
    phoneme: "kuh",
    emoji: "🐱",
    color: "bg-orange-400",
    filterTheme: {
      shape: "cat ears",
      primaryColor: "#FFA726",
      accentColor: "#FF7043",
      eyeColor: "#4CAF50",
    },
  },
  D: {
    word: "Dog",
    phoneme: "duh",
    emoji: "🐶",
    color: "bg-sunny-500",
    filterTheme: {
      shape: "dog snout",
      primaryColor: "#C8A26B",
      accentColor: "#8D6E63",
      eyeColor: "#5D4037",
    },
  },
  E: {
    word: "Elephant",
    phoneme: "ehh",
    emoji: "🐘",
    color: "bg-purple-300",
    filterTheme: {
      shape: "elephant trunk",
      primaryColor: "#9E9E9E",
      accentColor: "#757575",
      eyeColor: "#37474F",
    },
  },
  F: {
    word: "Fish",
    phoneme: "fff",
    emoji: "🐟",
    color: "bg-sky-300",
    filterTheme: {
      shape: "fish scales",
      primaryColor: "#4FC3F7",
      accentColor: "#0288D1",
      eyeColor: "#01579B",
    },
  },
  G: {
    word: "Grapes",
    phoneme: "guh",
    emoji: "🍇",
    color: "bg-purple-500",
    filterTheme: {
      shape: "grape cluster",
      primaryColor: "#9C27B0",
      accentColor: "#6A1B9A",
      eyeColor: "#F3E5F5",
    },
  },
  H: {
    word: "Hat",
    phoneme: "huh",
    emoji: "🎩",
    color: "bg-gray-700",
    filterTheme: {
      shape: "top hat",
      primaryColor: "#424242",
      accentColor: "#212121",
      eyeColor: "#BDBDBD",
    },
  },
  I: {
    word: "Ice cream",
    phoneme: "eye",
    emoji: "🍦",
    color: "bg-pink-300",
    filterTheme: {
      shape: "ice cream swirl",
      primaryColor: "#F48FB1",
      accentColor: "#F06292",
      eyeColor: "#880E4F",
    },
  },
  J: {
    word: "Jellyfish",
    phoneme: "juh",
    emoji: "🪼",
    color: "bg-purple-200",
    filterTheme: {
      shape: "jellyfish tentacles",
      primaryColor: "#CE93D8",
      accentColor: "#AB47BC",
      eyeColor: "#4A148C",
    },
  },
  K: {
    word: "Kite",
    phoneme: "kuh",
    emoji: "🪁",
    color: "bg-coral-300",
    filterTheme: {
      shape: "kite diamond",
      primaryColor: "#FF9E98",
      accentColor: "#FF6B63",
      eyeColor: "#C8160C",
    },
  },
  L: {
    word: "Lion",
    phoneme: "lll",
    emoji: "🦁",
    color: "bg-sunny-400",
    filterTheme: {
      shape: "lion mane",
      primaryColor: "#FDD835",
      accentColor: "#F57F17",
      eyeColor: "#E65100",
    },
  },
  M: {
    word: "Moon",
    phoneme: "mmm",
    emoji: "🌙",
    color: "bg-indigo-300",
    filterTheme: {
      shape: "crescent moon",
      primaryColor: "#7986CB",
      accentColor: "#3949AB",
      eyeColor: "#1A237E",
    },
  },
  N: {
    word: "Nose",
    phoneme: "nnn",
    emoji: "👃",
    color: "bg-orange-300",
    filterTheme: {
      shape: "nose bump",
      primaryColor: "#FFCC80",
      accentColor: "#FFA726",
      eyeColor: "#E65100",
    },
  },
  O: {
    word: "Orange",
    phoneme: "ohh",
    emoji: "🍊",
    color: "bg-orange-500",
    filterTheme: {
      shape: "orange slice",
      primaryColor: "#FF9800",
      accentColor: "#E65100",
      eyeColor: "#BF360C",
    },
  },
  P: {
    word: "Penguin",
    phoneme: "puh",
    emoji: "🐧",
    color: "bg-sky-800",
    filterTheme: {
      shape: "penguin beak",
      primaryColor: "#1A237E",
      accentColor: "#FFFFFF",
      eyeColor: "#FDD835",
    },
  },
  Q: {
    word: "Queen",
    phoneme: "kwuh",
    emoji: "👑",
    color: "bg-sunny-300",
    filterTheme: {
      shape: "crown",
      primaryColor: "#FDD835",
      accentColor: "#F9A825",
      eyeColor: "#BF360C",
    },
  },
  R: {
    word: "Rainbow",
    phoneme: "rrr",
    emoji: "🌈",
    color: "bg-coral-500",
    filterTheme: {
      shape: "rainbow arc",
      primaryColor: "#FF3D33",
      accentColor: "#FDD835",
      eyeColor: "#0288D1",
    },
  },
  S: {
    word: "Star",
    phoneme: "sss",
    emoji: "⭐",
    color: "bg-sunny-500",
    filterTheme: {
      shape: "star points",
      primaryColor: "#FDD835",
      accentColor: "#F57F17",
      eyeColor: "#1A237E",
    },
  },
  T: {
    word: "Train",
    phoneme: "tuh",
    emoji: "🚂",
    color: "bg-coral-600",
    filterTheme: {
      shape: "train conductor hat",
      primaryColor: "#ED1F14",
      accentColor: "#212121",
      eyeColor: "#FDD835",
    },
  },
  U: {
    word: "Umbrella",
    phoneme: "uhh",
    emoji: "☂️",
    color: "bg-purple-400",
    filterTheme: {
      shape: "umbrella dome",
      primaryColor: "#AB47BC",
      accentColor: "#6A1B9A",
      eyeColor: "#F3E5F5",
    },
  },
  V: {
    word: "Volcano",
    phoneme: "vvv",
    emoji: "🌋",
    color: "bg-orange-700",
    filterTheme: {
      shape: "volcano peak",
      primaryColor: "#F57C00",
      accentColor: "#BF360C",
      eyeColor: "#FFCC80",
    },
  },
  W: {
    word: "Watermelon",
    phoneme: "wuh",
    emoji: "🍉",
    color: "bg-grass-500",
    filterTheme: {
      shape: "watermelon slice",
      primaryColor: "#EF5350",
      accentColor: "#388E3C",
      eyeColor: "#212121",
    },
  },
  X: {
    word: "Xylophone",
    phoneme: "ksss",
    emoji: "🎵",
    color: "bg-coral-300",
    filterTheme: {
      shape: "musical bars",
      primaryColor: "#FF9E98",
      accentColor: "#FF3D33",
      eyeColor: "#1D3557",
    },
  },
  Y: {
    word: "Yarn",
    phoneme: "yuh",
    emoji: "🧶",
    color: "bg-sunny-300",
    filterTheme: {
      shape: "yarn ball",
      primaryColor: "#FDD835",
      accentColor: "#F9A825",
      eyeColor: "#880E4F",
    },
  },
  Z: {
    word: "Zebra",
    phoneme: "zzz",
    emoji: "🦓",
    color: "bg-gray-800",
    filterTheme: {
      shape: "zebra stripes",
      primaryColor: "#212121",
      accentColor: "#FFFFFF",
      eyeColor: "#37474F",
    },
  },
};
